"use client";

/**
 * The freeform collage Canvas, shared by the /outfits builder and the /home
 * daily plan's "Adjust this segment" editor. It lived inside outfits-view.tsx
 * until Phase 6.1 收尾; both surfaces now need identical drag/resize/z-order
 * behavior, and two copies would drift.
 *
 * Everything here is deliberately generic over `CanvasItem` — the minimal shape
 * both `WardrobeItem` (database row) and `DailyWardrobeItem` (daily plan API)
 * already satisfy — so neither caller has to convert its data first.
 */

import Image from "next/image";
import { useRef, useState, type DragEvent } from "react";
import type { PointerEvent as ReactPointerEvent } from "react";
import { Layers3, Maximize2, Plus, Search, Shirt, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { ITEM_CATEGORIES, type ItemCategory } from "@/types/database";

export interface CanvasItem {
  id: string;
  category: string;
  subcategory?: string | null;
  color?: string | null;
  clean_url: string | null;
  original_url: string;
}

/** Percentages of the square canvas, not pixels — the canvas is responsive. */
export interface CanvasItemLayout {
  x: number;
  y: number;
  width: number;
}

export type DragPayload =
  | { source: "closet"; itemId: string }
  | { source: "canvas"; itemId: string; index: number };

export function itemName(item: CanvasItem) {
  return item.subcategory || item.category;
}

export function imageUrl(item: CanvasItem) {
  return item.clean_url || item.original_url;
}

export function writeDragPayload(event: DragEvent, payload: DragPayload) {
  event.dataTransfer.setData("application/x-wardrobe-item", JSON.stringify(payload));
  event.dataTransfer.setData("text/plain", payload.itemId);
}

export function readDragPayload(event: DragEvent): DragPayload | null {
  try {
    const raw = event.dataTransfer.getData("application/x-wardrobe-item");
    return raw ? (JSON.parse(raw) as DragPayload) : null;
  } catch {
    return null;
  }
}

/**
 * Deterministic fallback placement, used both for newly added items and for
 * rows persisted before x/y/width existed (or generated by the AI, which never
 * produces layout).
 */
export function defaultLayoutFor(index: number): CanvasItemLayout {
  const defaultWidth = index >= 6 ? 22 : 28;
  const columns = index >= 6 ? 4 : 3;
  const column = index % columns;
  const row = Math.floor(index / columns);
  const horizontalStep = (94 - defaultWidth) / (columns - 1);
  return {
    x: 3 + column * horizontalStep,
    y: 4 + (row % 3) * 31,
    width: defaultWidth,
  };
}

/**
 * Build a full layout map from rows that may or may not carry geometry, keeping
 * each item's own saved position and only filling gaps from the default grid.
 */
export function layoutsFromRows(
  rows: { id: string; x?: number | null; y?: number | null; width?: number | null }[]
): Record<string, CanvasItemLayout> {
  const layouts: Record<string, CanvasItemLayout> = {};
  rows.forEach((row, index) => {
    const fallback = defaultLayoutFor(index);
    layouts[row.id] = {
      x: row.x ?? fallback.x,
      y: row.y ?? fallback.y,
      width: row.width ?? fallback.width,
    };
  });
  return layouts;
}

export function OutfitCanvas({
  items,
  layouts,
  isOver,
  onOver,
  onDrop,
  onRemove,
  onMove,
  onLayoutChange,
}: {
  items: CanvasItem[];
  layouts: Record<string, CanvasItemLayout>;
  isOver: boolean;
  onOver: (value: boolean) => void;
  onDrop: (event: DragEvent<HTMLDivElement>) => void;
  onRemove: (id: string) => void;
  onMove: (from: number, to: number) => void;
  onLayoutChange: (id: string, layout: CanvasItemLayout) => void;
}) {
  const canvasRef = useRef<HTMLDivElement>(null);
  const [gesture, setGesture] = useState<{
    itemId: string;
    mode: "move" | "resize";
    startClientX: number;
    startClientY: number;
    startLayout: CanvasItemLayout;
  } | null>(null);

  function startGesture(
    event: ReactPointerEvent<HTMLElement>,
    itemId: string,
    index: number,
    mode: "move" | "resize"
  ) {
    if (event.pointerType === "mouse" && event.button !== 0) return;
    const layout = layouts[itemId];
    if (!layout) return;
    event.preventDefault();
    event.stopPropagation();
    event.currentTarget.setPointerCapture(event.pointerId);
    setGesture({
      itemId,
      mode,
      startClientX: event.clientX,
      startClientY: event.clientY,
      startLayout: layout,
    });
    if (index !== items.length - 1) onMove(index, items.length - 1);
  }

  function updateGesture(event: ReactPointerEvent<HTMLElement>) {
    if (!gesture || !canvasRef.current) return;
    event.preventDefault();
    const rect = canvasRef.current.getBoundingClientRect();
    const deltaX = event.clientX - gesture.startClientX;
    const deltaY = event.clientY - gesture.startClientY;

    if (gesture.mode === "move") {
      const itemHeight = (gesture.startLayout.width * rect.width) / rect.height;
      onLayoutChange(gesture.itemId, {
        ...gesture.startLayout,
        x: Math.max(
          0,
          Math.min(
            100 - gesture.startLayout.width,
            gesture.startLayout.x + (deltaX / rect.width) * 100
          )
        ),
        y: Math.max(
          0,
          Math.min(100 - itemHeight, gesture.startLayout.y + (deltaY / rect.height) * 100)
        ),
      });
      return;
    }

    const resizeDelta = (Math.max(deltaX, deltaY) / rect.width) * 100;
    const maxWidthFromRight = 100 - gesture.startLayout.x;
    const maxWidthFromBottom = ((100 - gesture.startLayout.y) * rect.height) / rect.width;
    const maxWidth = Math.min(60, maxWidthFromRight, maxWidthFromBottom);
    onLayoutChange(gesture.itemId, {
      ...gesture.startLayout,
      width: Math.max(15, Math.min(maxWidth, gesture.startLayout.width + resizeDelta)),
    });
  }

  function endGesture(event: ReactPointerEvent<HTMLElement>) {
    if (!gesture) return;
    if (event.currentTarget.hasPointerCapture(event.pointerId)) {
      event.currentTarget.releasePointerCapture(event.pointerId);
    }
    setGesture(null);
  }

  return (
    <section className="rounded-2xl border border-surface-200 bg-[#f1eee9] p-3 sm:p-5">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2 text-xs font-semibold text-surface-600">
          <Layers3 size={15} /> Outfit canvas
        </div>
        <div className="text-right">
          <span className="block text-[10px] font-medium text-surface-500">
            {items.length} {items.length === 1 ? "piece" : "pieces"}
          </span>
          <span className="block text-[9px] text-surface-400">Drag to move · corner to resize</span>
        </div>
      </div>
      <div
        ref={canvasRef}
        onDragEnter={(event) => {
          event.preventDefault();
          onOver(true);
        }}
        onDragOver={(event) => {
          event.preventDefault();
          event.dataTransfer.dropEffect = "copy";
        }}
        onDragLeave={(event) => {
          if (!event.currentTarget.contains(event.relatedTarget as Node | null)) onOver(false);
        }}
        onDrop={onDrop}
        className={cn(
          "relative aspect-square overflow-hidden rounded-xl border-2 bg-white transition-all",
          isOver
            ? "scale-[1.01] border-brand-400 bg-brand-50 shadow-lg shadow-brand-900/5"
            : "border-dashed border-surface-300"
        )}
      >
        <div className="pointer-events-none absolute inset-0 opacity-[0.035] [background-image:linear-gradient(to_right,#292524_1px,transparent_1px),linear-gradient(to_bottom,#292524_1px,transparent_1px)] [background-size:32px_32px]" />
        {items.length === 0 ? (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center p-8 text-center">
            <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-surface-100 text-surface-400">
              <Shirt size={28} strokeWidth={1.5} />
            </div>
            <h3 className="text-sm font-semibold text-surface-700">Start building your look</h3>
            <p className="mt-1 max-w-56 text-xs leading-5 text-surface-400">
              Drag pieces here from your closet, or tap the + button on any item.
            </p>
          </div>
        ) : (
          items.map((item, index) => {
            const layout = layouts[item.id];
            if (!layout) return null;
            const isActive = gesture?.itemId === item.id;
            return (
              <div
                key={item.id}
                onPointerDown={(event) => {
                  if ((event.target as HTMLElement).closest("button")) return;
                  startGesture(event, item.id, index, "move");
                }}
                onPointerMove={updateGesture}
                onPointerUp={endGesture}
                onPointerCancel={endGesture}
                className={cn(
                  "group absolute touch-none select-none bg-transparent p-0 transition-[filter]",
                  isActive ? "cursor-grabbing drop-shadow-xl" : "cursor-grab hover:drop-shadow-lg"
                )}
                style={{
                  left: `${layout.x}%`,
                  top: `${layout.y}%`,
                  width: `${layout.width}%`,
                  aspectRatio: "1 / 1",
                  zIndex: index + 10,
                }}
              >
                <div className="relative h-full w-full">
                  <Image
                    src={imageUrl(item)}
                    alt={`${item.color || ""} ${itemName(item)}`}
                    fill
                    className="pointer-events-none object-contain"
                    sizes="180px"
                    unoptimized
                    draggable={false}
                  />
                </div>
                <button
                  type="button"
                  onClick={() => onRemove(item.id)}
                  className="absolute -right-1.5 -top-1.5 z-20 flex h-6 w-6 items-center justify-center rounded-full bg-white text-surface-400 opacity-100 shadow-md transition-all hover:bg-red-50 hover:text-red-500 sm:opacity-0 sm:group-hover:opacity-100"
                  aria-label={`Remove ${itemName(item)}`}
                >
                  <X size={13} />
                </button>
                <button
                  type="button"
                  onPointerDown={(event) => startGesture(event, item.id, index, "resize")}
                  onPointerMove={updateGesture}
                  onPointerUp={endGesture}
                  onPointerCancel={endGesture}
                  className="absolute -bottom-1.5 -right-1.5 z-20 flex h-7 w-7 touch-none items-center justify-center rounded-lg bg-white text-surface-500 opacity-100 shadow-md transition-all hover:text-brand-600 sm:opacity-0 sm:group-hover:opacity-100"
                  aria-label={`Resize ${itemName(item)}`}
                >
                  <Maximize2 size={13} />
                </button>
              </div>
            );
          })
        )}
      </div>
    </section>
  );
}

export function ClosetPicker({
  items,
  activeCategory,
  search,
  onSearch,
  onCategory,
  onAdd,
  minHeightClass = "min-h-[620px]",
  maxListHeightClass = "max-h-[520px]",
}: {
  items: CanvasItem[];
  activeCategory: ItemCategory | "All";
  search: string;
  onSearch: (value: string) => void;
  onCategory: (value: ItemCategory | "All") => void;
  onAdd: (id: string) => void;
  minHeightClass?: string;
  maxListHeightClass?: string;
}) {
  return (
    <section
      className={cn(
        "flex flex-col overflow-hidden rounded-2xl border border-surface-200 bg-white",
        minHeightClass
      )}
    >
      <div className="border-b border-surface-100 p-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-sm font-semibold text-surface-900">Your closet</h2>
            <p className="mt-0.5 text-xs text-surface-400">Drag or tap to add</p>
          </div>
          <span className="rounded-full bg-surface-100 px-2 py-1 text-[10px] font-semibold text-surface-500">
            {items.length} items
          </span>
        </div>
        <label className="mt-3 flex items-center gap-2 rounded-lg border border-surface-200 bg-surface-50 px-3 py-2 focus-within:border-brand-400 focus-within:ring-2 focus-within:ring-brand-100">
          <Search size={14} className="shrink-0 text-surface-400" />
          <input
            value={search}
            onChange={(event) => onSearch(event.target.value)}
            placeholder="Search color, brand, type…"
            className="w-full bg-transparent text-xs text-surface-800 outline-none placeholder:text-surface-400"
          />
        </label>
        <div className="scrollbar-hide mt-3 flex gap-1.5 overflow-x-auto pb-1">
          {["All", ...ITEM_CATEGORIES].map((category) => (
            <button
              type="button"
              key={category}
              onClick={() => onCategory(category as ItemCategory | "All")}
              className={cn(
                "whitespace-nowrap rounded-full px-2.5 py-1 text-[10px] font-medium transition-colors",
                activeCategory === category
                  ? "bg-surface-900 text-white"
                  : "bg-surface-100 text-surface-500 hover:bg-surface-200"
              )}
            >
              {category}
            </button>
          ))}
        </div>
      </div>

      <div
        className={cn(
          "scrollbar-hide grid flex-1 auto-rows-max grid-cols-2 content-start items-start gap-3 overflow-y-auto p-3",
          maxListHeightClass
        )}
      >
        {items.map((item) => (
          <button
            type="button"
            key={item.id}
            draggable
            onDragStart={(event) => {
              writeDragPayload(event, { source: "closet", itemId: item.id });
              event.dataTransfer.effectAllowed = "copy";
            }}
            onClick={() => onAdd(item.id)}
            className="group relative aspect-square w-full self-start overflow-hidden rounded-xl border border-surface-200 bg-surface-50 text-left transition-all hover:-translate-y-0.5 hover:border-surface-300 hover:shadow-sm"
            aria-label={`Add ${itemName(item)}`}
          >
            <div className="absolute inset-0">
              <Image
                src={imageUrl(item)}
                alt={`${item.color || ""} ${itemName(item)}`}
                fill
                className="object-contain p-2"
                sizes="(max-width: 1024px) 25vw, 150px"
                unoptimized
              />
            </div>
            <div className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-white via-white/90 to-transparent px-2 pb-1.5 pt-5">
              <p className="truncate text-[10px] font-medium text-surface-700">{itemName(item)}</p>
            </div>
            <span className="absolute right-2 top-2 flex h-6 w-6 items-center justify-center rounded-full bg-white/90 text-surface-500 shadow-sm transition-colors group-hover:bg-surface-900 group-hover:text-white">
              <Plus size={13} />
            </span>
          </button>
        ))}
        {items.length === 0 && (
          <div className="col-span-2 flex min-h-48 flex-col items-center justify-center text-center">
            <Shirt size={24} className="mb-2 text-surface-300" />
            <p className="text-xs text-surface-400">No matching pieces</p>
          </div>
        )}
      </div>
    </section>
  );
}

/**
 * Read-only render of an arranged collage, for surfaces that display a look
 * without editing it (the /home daily plan). Uses the same percentage geometry
 * and the same default-grid fallback as the editable Canvas, so what the user
 * arranged is what they see afterwards.
 */
export function OutfitCollage({
  items,
  layouts,
  className,
}: {
  items: CanvasItem[];
  layouts: Record<string, CanvasItemLayout>;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "relative aspect-square w-full overflow-hidden rounded-xl bg-surface-50",
        className
      )}
    >
      {items.map((item, index) => {
        const layout = layouts[item.id] || defaultLayoutFor(index);
        return (
          <div
            key={item.id}
            className="absolute"
            style={{
              left: `${layout.x}%`,
              top: `${layout.y}%`,
              width: `${layout.width}%`,
              aspectRatio: "1 / 1",
              zIndex: index + 10,
            }}
          >
            <Image
              src={imageUrl(item)}
              alt={`${item.color || ""} ${itemName(item)}`}
              fill
              className="object-contain"
              sizes="180px"
              unoptimized
            />
          </div>
        );
      })}
    </div>
  );
}
